[configurations.zsh]
render = [
    { source = ".zshrc", destination = "~/.zshrc" },
    { source = "aliases.zsh", destination = "~/.oh-my-zsh/custom/aliases.zsh" }
]

    [configurations.zsh.variables]
    shell = "zsh"