[configurations.window-binds]
render = [
    { source = "udevmon.yaml", destination = "/etc/interception/udevmon.yaml", as = "root" },
    { source = "fix-niri-altdrag", destination = "/etc/interception/fix-niri-altdrag", as = "root", action = "copy", permissions="0755" }
]

# Post-install: run `sudo systemctl enable --now udevmon`
# Post-reload: run `sudo systemctl restart udevmon`