imports = [
    "interception-tools/window-binds.toml",
    "wallpaper/swww.toml",
    "lightdm/lightdm.toml"
]

[configurations.niri]
render = [
    { source = "config.kdl", destination = "~/.config/niri/config.kdl" }
]
subconfigs = ["window-binds", "swww", "lightdm"]
