imports = [
    "interception-tools/window-binds.toml",
    "wallpaper/swww.toml",
    "lightdm/lightdm.toml",
    "bar/bar.toml"
]

[configurations.niri]
render = [
    { source = "config.kdl", destination = "~/.config/niri/config.kdl" },
    { source = "compat/brave-flags.conf", destination = "~/.config/brave-flags.conf" }
]
subconfigs = ["window-binds", "swww", "lightdm", "bar"]
