imports = [
    "interception-tools/window-binds.toml"
]

[configurations.niri]
render = [
    { source = "config.kdl", destination = "~brody/.config/niri/config.kdl" }
]
subconfigs = ["window-binds"]
