[configurations.bar]
render = [
    # lol temporary
    { source = "../../../bar/target/debug/bar", destination = "/usr/local/bin/bar", action = "copy", as = "root", owner = "brody", permissions = "0755" },
]