# Backups
IgnorePath '/.snapshots' # Snapshots directory, not needed for syncing

# Pretty much everything in /var is unimportant
IgnorePath '/var'

# Directories made for temporary files
IgnorePath '/tmp'
IgnorePath '/run'
IgnorePath '/.cache' # User cache directory, not needed for syncing

# Stuff in /usr is generally generated or not needed for syncing
IgnorePath '/usr'

# Stuff in /boot that we don't want to sync
IgnorePath '/boot/grub' # Generated by grub
IgnorePath '/boot/EFI' # EFI partition, not needed for syncing
IgnorePath '/boot/System Volume Information' # Made by Windows, not needed for syncing
# kernels
IgnorePath '/boot/vmlinuz*' # Linux kernel images
IgnorePath '/boot/initrd*' # Initial ramdisk images
IgnorePath '/boot/initramfs*' # Initial ramdisk images
IgnorePath '/boot/config*' # Kernel configuration files
IgnorePath '/boot/System.map*' # Kernel symbol maps

# Stuff in /etc that we don't want to sync
IgnorePath '/etc/ssh/ssh_host_*_key' # SSH host keys
IgnorePath '/etc/ssh/ssh_host_*_key.pub' # SSH host public keys
IgnorePath '/etc/ssh/moduli' # SSH moduli file
IgnorePath '/etc/ca-certificates'
IgnorePath '/etc/ssl'
IgnorePath '/etc/pacman.d/gnupg' # Pacman GPG keys
IgnorePath '/etc/.updated'
IgnorePath '/etc/fstab' # Filesystem table, generated by the system
IgnorePath '/etc/mtab' # Mount table, generated by the system
IgnorePath '/etc/crypttab' # Encrypted volumes configuration, generated by the system
IgnorePath '/etc/adjtime' # Hardware clock configuration, generated by the system
IgnorePath '/etc/locale.conf' # Locale configuration, generated by the system
IgnorePath '/etc/localtime' # Timezone configuration, generated by the system
# Password files
IgnorePath '/etc/passwd*'
IgnorePath '/etc/shadow*'

# Generated files
IgnorePath '/etc/machine-id' # Machine ID, generated by the system

# Hostname-specific files
IgnorePath '/etc/hostname' # Hostname file
IgnorePath '/etc/hosts' # Hosts file
IgnorePath '/etc/resolv.conf' # DNS resolver configuration