# Generated by dotmgr
IgnorePath '/home/brody/.zshrc'
IgnorePath '/home/brody/.oh-my-zsh/custom/aliases.zsh'
IgnorePath '/home/brody/.config/niri/config.kdl'
IgnorePath '/etc/interception/udevmon.yaml'
IgnorePath '/etc/interception/fix-niri-altdrag'
