# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

{% if device == "laptop" %}
background {
    path = screenshot # We can use this because we're not using Nvidia hardware.
    blur_passes = 3
    blur_size = 2
}
{% endif %}

general {
    hide_cursor = true
    immediate_render = false
}

# https://wiki.hypr.land/Configuring/Animations/
bezier = easeInOutSine, 0.37, 0, 0.63, 1
animation = fadeIn, 1, 2, easeInOutSine
animation = fadeOut, 1, 1, easeInOutSine

{% if device == "laptop" %}
auth = {
    fingerprint:enabled = true
    fingerprint:ready_message = Scan fingerprint
    fingerprint:present_message = Scanning fingerprint...
}
{% endif %}

input-field {
    monitor = 
    size = 350, 55
    outline_thickness = 2
    # Scale of input-field height, 0.2 - 0.8
    dots_size = 0.2
    # Scale of dots' absolute size, 0.0 - 1.0
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    rounding = 10
    check_color = rgba(201, 177, 140, 0.3)
    placeholder_text = <i><span foreground="##cdd6f4">Password...</span></i>
    hide_input = false
    position = 0, -150
    halign = center
    valign = center
}

# Positive positions are upward
label { # Date
    monitor = 
    text = cmd[update:1000] date +"%A, %B %d"
    color = rgba(242, 243, 244, 0.75)
    font_size = 22
    font_family = JetBrains Mono
    position = 0, 200
    halign = center
    valign = center
    zindex = 5
}
label { # Date shadow
    monitor = 
    text = cmd[update:1000] date +"%A, %B %d"
    color = rgba(0, 0, 0, 0.75)
    font_size = 22
    font_family = JetBrains Mono
    position = 2, 198
    halign = center
    valign = center
    zindex = 4
}

label { # Time
    monitor = 
    text = cmd[update:1000] date +"%-I:%M"
    color = rgba(242, 243, 244, 0.75)
    font_size = 95
    font_family = JetBrains Mono Extrabold
    position = 0, 100
    halign = center
    valign = center
    zindex = 5
}
label { # Time shadow
    monitor = 
    text = cmd[update:1000] date +"%-I:%M"
    color = rgba(0, 0, 0, 0.75)
    font_size = 95
    font_family = JetBrains Mono Extrabold
    position = 4, 96
    halign = center
    valign = center
    zindex = 4
}

label { # User
    monitor = 
    text = cmd[update:1000] sh ~/.local/bin/userInfo.sh
    color = rgba(255, 255, 255, 0.8)
    font_size = 18
    font_family = JetBrains Mono
    position = 0, 40
    halign = center
    valign = bottom
}

{% if device == "laptop" %}
label {
    monitor = 
    text = $FPRINTPROMPT
    color = rgba(242, 243, 244, 0.75)
    font_size = 22
    font_family = JetBrains Mono
    position = 0, -80
    halign = center
    valign = center
    zindex = 5
}

label { # Battery percentage
    monitor = 
    text = cmd[update:1000] sh ~/.local/bin/battery.sh
    font_size = 18
    font_family = JetBrains Mono
    position = -15, -15
    halign = right
    valign = top
}
{% endif %}