// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopFile = { file_name: string, name: string | null, comment: string | null, app_type: string | null, startup_wm_class: string | null, exec: string | null, icon_path: string | null, categories: Array<string>, keywords: Array<string>, no_display: boolean | null, };
