// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkManagerState = { status: NetworkStatus, };

export type NetworkStatus = "WiredConnected" | "WifiConnected" | "CellularConnected" | "VpnConnected" | "WifiDisconnected" | "Offline" | "Unknown";
