// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { id: number, application_name: string, application_icon_path: string | null, title: string, body: string, actions: Array<NotificationAction>, urgency: NotificationUrgency, };

export type NotificationAction = { action_key: string, label: string, };

export type NotificationUrgency = "Low" | "Normal" | "Critical";
