// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatteryState = "Unknown" | "Charging" | "Discharging" | "Empty" | "FullyCharged" | "PendingCharge" | "PendingDischarge";

/**
 * See https://upower.freedesktop.org/docs/Device.html for documentation on the interface, and
 * see https://upower.freedesktop.org/docs/UPower.html for documentaation on the display device.
 * Since this only references the display device from UPower, only some properties are set:
 * Type: the type of the display device, UPS or Battery. Note that this value can change, as opposed to real devices.
 * State: the power state of the display device, such as Charging or Discharging.
 * Percentage: the amount of energy left on the device.
 * Energy: Amount of energy (measured in Wh) currently available in the power source.
 * EnergyFull: Amount of energy (measured in Wh) in the power source when it's considered full.
 * EnergyRate: Discharging/charging rate of the source, measured in Watt.
 * TimeToEmpty: Number of seconds until the power source is considered empty.
 * TimeToFull: Number of seconds until the power source is considered full.
 * IsPresent: Whether a status icon using this information should be presented. (Takes a special meaning)
 * IconName: An icon name representing the device state.
 * WarningLevel: The same as the overall WarningLevel
 */
export type UpowerProperties = { 
/**
 * The battery power state.
 */
state: BatteryState, 
/**
 * The amount of energy left in the power source expressed as a percentage between 0 and 100.
 * Typically this is the same as (energy - energy-empty) / (energy-full - energy-empty).
 * However, some primitive power sources are capable of only reporting percentages and in
 * this case the energy-* properties will be unset while this property is set.
 * 
 * The percentage will still exist as an approximation if the device only supports coarse
 * reporting, so we don't need to worry about that.
 */
percentage: number, 
/**
 * Amount of energy (measured in Wh) currently available in the power source.
 */
energy: number, 
/**
 * Amount of energy (measured in Wh) in the power source when it's considered full.
 */
energy_full: number, 
/**
 * Discharging/charging rate of the source, measured in Watt.
 */
energy_rate: number, 
/**
 * Number of seconds until the power source is considered empty. Set to 0 if unknown. 
 */
time_to_empty: bigint, 
/**
 * Number of seconds until the power source is considered full. Set to 0 if unknown. 
 */
time_to_full: bigint, 
/**
 * This takes a special meaning compared to real devices!
 * Set to true if battery information should be presented to the user.
 */
is_present: boolean, 
/**
 * An icon name, following the Icon Naming Specification.
 * Note that the icons might not match end-user expectations in terms of
 * presentation relative to the amount of battery left or perceived to be left.
 * It is recommended that front-ends use the BatteryLevel property first,
 * if available, followed by the Percentage, to present a more realistic battery level to the user. 
 */
icon_name: string, };
